---
# defaults file for roles/postgresql-server
postgres_rhel_repo: "{{ postgres_rhel8_repo }}"

postgres_packages:
  - postgresql12 
  - postgresql12-server 
  - postgresql12-contrib 
  - postgresql12-libs
postgres_library: python3-psycopg2
postgres_12_data_dir: /var/lib/pgsql/12/data
postgres_12_bin_path: /usr/pgsql-12/bin
postgres_service: postgresql-12.service
postgres_port: 5432
postgres_user: postgres
postgres_users: []
postgres_databases: []