- name: Smoke Test - End to End - Database Servers
  hosts: database_servers
  gather_facts: true
  become: true

  tasks:
    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "127.0.0.1"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      loop: "{{ groups.database_servers }}"
      delegate_to: "{{ item }}"

- name: Smoke Test - End to End - LB Servers
  hosts: load_balancers
  gather_facts: true
  become: false

  tasks:
    - name: Smoketest Load Balancer
      uri:
        url: "http://{{ item }}/ping"
        return_content: yes
      until: '"alive" in result.content'
      retries: 10
      delay: 1
      register: result
      delegate_to: localhost
      loop: "{{ groups.load_balancers }}"
